// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqOV61aOM8fQuixpNHKr8Cr35xDW4nz-k',
    appId: '1:589876337034:web:cf7d4b83e44545385e9073',
    messagingSenderId: '589876337034',
    projectId: 'bulgarian-learning-app',
    authDomain: 'bulgarian-learning-app.firebaseapp.com',
    storageBucket: 'bulgarian-learning-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIvtSntILoLtuvnM2RhqLdIU9GNlQS96Q',
    appId: '1:589876337034:android:afc4bfc9a7cbda8f5e9073',
    messagingSenderId: '589876337034',
    projectId: 'bulgarian-learning-app',
    storageBucket: 'bulgarian-learning-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCBH3MxfzpWsaBXqCMsit0Rg4oP0EMEz0',
    appId: '1:589876337034:ios:fb0e14d05f9079be5e9073',
    messagingSenderId: '589876337034',
    projectId: 'bulgarian-learning-app',
    storageBucket: 'bulgarian-learning-app.firebasestorage.app',
    iosBundleId: 'com.example.bulgarianApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCBH3MxfzpWsaBXqCMsit0Rg4oP0EMEz0',
    appId: '1:589876337034:ios:fb0e14d05f9079be5e9073',
    messagingSenderId: '589876337034',
    projectId: 'bulgarian-learning-app',
    storageBucket: 'bulgarian-learning-app.firebasestorage.app',
    iosBundleId: 'com.example.bulgarianApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqOV61aOM8fQuixpNHKr8Cr35xDW4nz-k',
    appId: '1:589876337034:web:b8cde8c4c7c81f855e9073',
    messagingSenderId: '589876337034',
    projectId: 'bulgarian-learning-app',
    authDomain: 'bulgarian-learning-app.firebaseapp.com',
    storageBucket: 'bulgarian-learning-app.firebasestorage.app',
  );
}
